name: Atualiza ranking Tibia

on:
  schedule:
    - cron: '0 * * * *'  # roda a cada hora
  workflow_dispatch:  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Faz checkout do código
      uses: actions/checkout@v3

    - name: Configura Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instala dependências Python
      run: pip install -r requirements.txt
    
    - name: Instala Playwright e dependências de SO
        run: |
          # instala o pacote python-playwright (deve já estar no requirements, mas reforçamos)
          pip install playwright
          # instala os navegadores necessários e as libs nativas
          python3 -m playwright install --with-deps

    - name: Executa coleta e ranking
      run: |
        python3 scripts/coleta_validada_pronto.py
        python3 scripts/gerar_ranking_ordenado.py

    - name: Comita e envia resultados
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add resultado_validado.csv ranking_final.csv
        git commit -m "Atualiza ranking automático" || echo "Sem alterações"
        git push
